#!/bin/bash
set -e

if [ "$DOCKER_TAG" == "latest" ] ; then 
    docker build --build-arg PHP_VERSION=7.3 --target=production -t $DOCKER_REPO:latest .
    docker build --build-arg PHP_VERSION=7.3 --target=development -t $DOCKER_REPO:dev .

    docker build --build-arg PHP_VERSION=7.3 --target=production -t $DOCKER_REPO:7.3 .
    docker build --build-arg PHP_VERSION=7.3 --target=development -t $DOCKER_REPO:7.3-dev .

    docker build --build-arg PHP_VERSION=7.4 --target=production -t $DOCKER_REPO:7.4 .
    docker build --build-arg PHP_VERSION=7.4 --target=development -t $DOCKER_REPO:7.4-dev .

else
    docker build --build-arg PHP_VERSION=7.3 --target=production -t $DOCKER_REPO:$DOCKER_TAG .
    docker build --build-arg PHP_VERSION=7.3 --target=production -t $DOCKER_REPO:$DOCKER_TAG-dev .

    docker build --build-arg PHP_VERSION=7.3 --target=production -t $DOCKER_REPO:$DOCKER_TAG-7.3 .
    docker build --build-arg PHP_VERSION=7.3 --target=development -t $DOCKER_REPO:$DOCKER_TAG-7.3-dev .

    docker build --build-arg PHP_VERSION=7.4 --target=production -t $DOCKER_REPO:$DOCKER_TAG-7.4 .
    docker build --build-arg PHP_VERSION=7.4 --target=development -t $DOCKER_REPO:$DOCKER_TAG-7.4-dev .
fi

